// Generated by gencpp from file uart_lib/usr_message.msg
// DO NOT EDIT!


#ifndef UART_LIB_MESSAGE_USR_MESSAGE_H
#define UART_LIB_MESSAGE_USR_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/UInt8MultiArray.h>

namespace uart_lib
{
template <class ContainerAllocator>
struct usr_message_
{
  typedef usr_message_<ContainerAllocator> Type;

  usr_message_()
    : rfid_mgs()  {
    }
  usr_message_(const ContainerAllocator& _alloc)
    : rfid_mgs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::UInt8MultiArray_<ContainerAllocator>  _rfid_mgs_type;
  _rfid_mgs_type rfid_mgs;




  typedef boost::shared_ptr< ::uart_lib::usr_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uart_lib::usr_message_<ContainerAllocator> const> ConstPtr;

}; // struct usr_message_

typedef ::uart_lib::usr_message_<std::allocator<void> > usr_message;

typedef boost::shared_ptr< ::uart_lib::usr_message > usr_messagePtr;
typedef boost::shared_ptr< ::uart_lib::usr_message const> usr_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uart_lib::usr_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uart_lib::usr_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uart_lib

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'uart_lib': ['/home/ubuntu/catkin_ws/src/uart_lib/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uart_lib::usr_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uart_lib::usr_message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uart_lib::usr_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uart_lib::usr_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uart_lib::usr_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uart_lib::usr_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uart_lib::usr_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "390e8dfdd8fdc4523e51bc8a3dbc8d7d";
  }

  static const char* value(const ::uart_lib::usr_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x390e8dfdd8fdc452ULL;
  static const uint64_t static_value2 = 0x3e51bc8a3dbc8d7dULL;
};

template<class ContainerAllocator>
struct DataType< ::uart_lib::usr_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uart_lib/usr_message";
  }

  static const char* value(const ::uart_lib::usr_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uart_lib::usr_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/UInt8MultiArray rfid_mgs\n\
\n\
================================================================================\n\
MSG: std_msgs/UInt8MultiArray\n\
# Please look at the MultiArrayLayout message definition for\n\
# documentation on all multiarrays.\n\
\n\
MultiArrayLayout  layout        # specification of data layout\n\
uint8[]           data          # array of data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding elements at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
";
  }

  static const char* value(const ::uart_lib::usr_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uart_lib::usr_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rfid_mgs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct usr_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uart_lib::usr_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uart_lib::usr_message_<ContainerAllocator>& v)
  {
    s << indent << "rfid_mgs: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.rfid_mgs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UART_LIB_MESSAGE_USR_MESSAGE_H
